# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='vk_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
